# Generated by Django 3.2 on 2021-04-19 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210408_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(blank=True, max_length=255, verbose_name='Адрес 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Адрес 2')),
                ('profile_picture', models.ImageField(blank=True, upload_to='user_profile', verbose_name='Фото')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Область')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
