# Generated by Django 3.2 on 2021-05-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_social_login',
            field=models.BooleanField(default=False, verbose_name='Из соц. сетей'),
        ),
    ]
