# Generated by Django 3.2 on 2021-05-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_account_is_social_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_social_login',
        ),
    ]
