# Generated by Django 3.2 on 2021-05-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_account_is_social_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='was_confirm_email',
            field=models.BooleanField(default=False, verbose_name='Подтверждена почта'),
        ),
    ]
