# Generated by Django 3.2 on 2021-05-18 18:01

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_account_was_confirm_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Аккаунт', 'verbose_name_plural': 'Аккаунты'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профайл', 'verbose_name_plural': 'Профайлы'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=smartfields.fields.ImageField(blank=True, default='user_profile/default.png', upload_to='user_profile', verbose_name='Фото'),
        ),
    ]
