# Generated by Django 3.2 on 2021-04-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210423_1218'),
        ('cart', '0004_remove_cartitem_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.ManyToManyField(blank=True, to='store.Color'),
        ),
    ]
