# Generated by Django 3.2 on 2021-04-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default=1, max_length=50, verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default=1, max_length=50, verbose_name='Область'),
            preserve_default=False,
        ),
    ]
