# Generated by Django 3.2 on 2021-04-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210416_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_note',
            field=models.TextField(blank=True, max_length=500, verbose_name='Примечания'),
        ),
    ]
