# Generated by Django 3.2 on 2021-04-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Подтверждён', 'Подтверждён'), ('Завершён', 'Завершён'), ('Отменён', 'Отменён')], default='Новый', max_length=20, verbose_name='Статус'),
        ),
    ]
