# Generated by Django 3.2 on 2021-04-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210423_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_amount',
            field=models.IntegerField(default=1, verbose_name='Размер скидки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_discount',
            field=models.BooleanField(default=True, verbose_name='Скидка?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, verbose_name='Слаг'),
        ),
    ]
