# Generated by Django 3.2 on 2021-04-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210423_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgallery',
            old_name='images',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='is_active',
        ),
        migrations.AddField(
            model_name='variation',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='В наличии'),
            preserve_default=False,
        ),
    ]
