# Generated by Django 3.2 on 2021-04-23 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20210423_1325'),
        ('orders', '0008_auto_20210423_1325'),
        ('store', '0015_auto_20210423_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallery',
            name='color',
        ),
        migrations.RemoveField(
            model_name='size',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='another_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Другой цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='Красный', max_length=100, verbose_name='Цвет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='size',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
