# Generated by Django 3.2 on 2021-04-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_product_another_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='another_color',
            field=models.ManyToManyField(blank=True, null=True, related_name='_store_product_another_color_+', to='store.Product', verbose_name='Другой цвет'),
        ),
    ]
