# Generated by Django 3.2 on 2021-05-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20210424_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=200, null=True, verbose_name='Актикул'),
        ),
        migrations.AddField(
            model_name='product',
            name='structure',
            field=models.TextField(blank=True, null=True, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img1',
            field=models.ImageField(upload_to='store/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.ImageField(upload_to='store/products'),
        ),
    ]
