# Generated by Django 3.2 on 2021-05-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20210515_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_of_model',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название модели'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=200, null=True, verbose_name='Артикул'),
        ),
    ]
