# Generated by Django 3.2 on 2021-05-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20210516_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'price', '-create_date'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='product',
            name='structure',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Состав'),
        ),
    ]
