# Generated by Django 3.2 on 2021-05-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_customerquestion_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'price', '-create_date'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
