# Generated by Django 3.2 on 2021-05-18 18:16

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img1',
            field=smartfields.fields.ImageField(upload_to='store/products', verbose_name='Изображение 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=smartfields.fields.ImageField(upload_to='store/products', verbose_name='Изображение 2'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=smartfields.fields.ImageField(upload_to='store/products', verbose_name='Изображение'),
        ),
    ]
