# Generated by Django 3.2 on 2021-05-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_name_for_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Наименование для категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_for_product',
            field=models.CharField(max_length=50, null=True, verbose_name='Наименование для продукта'),
        ),
    ]
